services:
  postgres:
    image: postgres:16.4
    container_name: upassed_answer_service_postgres
    environment:
      POSTGRES_DB: "upassed-answer-service-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
        - "5432:5432"
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: upassed_answer_service_jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: upassed_answer_service_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "upassed-rabbit-user"
      RABBITMQ_DEFAULT_PASS: "upassed-rabbit-password"
    ports:
      - "5672:5672"
      - "15672:15672"
