name: go microservice workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23  # Set the Go version according to your needs

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the project
      - name: Build the project
        run: go build ./...

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures the test job runs only after the build job completes successfully

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run unit tests
      - name: Run tests
        run: go test -v ./...

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/upassed-answer-service:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/upassed-answer-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Docker Container on Remote Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: root
          SERVER_PASSWORD: ${{ secrets.SERVER_ROOT_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            docker stop upassed-answer-service || true
            docker rm upassed-answer-service || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/upassed-answer-service:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/upassed-answer-service:latest
          
            docker run -d --name upassed-answer-service --network upassed \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_DATABASE_NAME=${{ secrets.POSTGRES_DATABASE_NAME }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e GRPC_SERVER_PORT=${{ secrets.GRPC_SERVER_PORT }} \
              -e GRPC_SERVER_TIMEOUT=${{ secrets.GRPC_SERVER_TIMEOUT }} \
              -e MIGRATIONS_PATH=${{ secrets.MIGRATIONS_PATH }} \
              -e MIGRATIONS_TABLE_NAME=${{ secrets.MIGRATIONS_TABLE_NAME }} \
              -e AUTHENTICATION_SERVICE_HOST=${{ secrets.AUTHENTICATION_SERVICE_HOST }} \
              -e AUTHENTICATION_SERVICE_PORT=${{ secrets.AUTHENTICATION_SERVICE_PORT }} \
              -e ENDPOINT_EXECUTION_TIMEOUT_MS=${{ secrets.ENDPOINT_EXECUTION_TIMEOUT_MS }} \
              -e JAEGER_HOST=${{ secrets.JAEGER_HOST }} \
              -e JAEGER_PORT=${{ secrets.JAEGER_PORT }} \
              -e ANSWER_TRACER_NAME=${{ secrets.ANSWER_TRACER_NAME }} \
              -e RABBIT_USER=${{ secrets.RABBIT_USER }} \
              -e RABBIT_PASSWORD=${{ secrets.RABBIT_PASSWORD }} \
              -e RABBIT_HOST=${{ secrets.RABBIT_HOST }} \
              -e RABBIT_PORT=${{ secrets.RABBIT_PORT }} \
              -e RABBIT_EXCHANGE_NAME=${{ secrets.RABBIT_EXCHANGE_NAME }} \
              -e RABBIT_EXCHANGE_TYPE=${{ secrets.RABBIT_EXCHANGE_TYPE }} \
              -e RABBIT_ANSWER_CREATE_QUEUE_NAME=${{ secrets.RABBIT_ANSWER_CREATE_QUEUE_NAME }} \
              -e RABBIT_ANSWER_CREATE_QUEUE_ROUTING_KEY=${{ secrets.RABBIT_ANSWER_CREATE_QUEUE_ROUTING_KEY }} \
              -p ${{ secrets.GRPC_SERVER_PORT }}:${{ secrets.GRPC_SERVER_PORT }} \
              ${{ secrets.DOCKER_USERNAME }}/upassed-answer-service:latest
          EOF
